---
- hosts: localhost
  connection: local
  become: true  # sudo

  tasks:
  - name: install dependencies
    package:
      name:
        - git
        - gcc

  - name: install cli programs
    package:
      name:
        - fzf
        - stow

  - name: download and install nvim 0.8
    ansible.builtin.get_url:
      url: "https://github.com/neovim/neovim/releases/download/v0.8.0/nvim.appimage"
      dest: /usr/local/bin/nvim
      mode: "0555"

  - name: check if cargo is installed
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: yes

  - name: Download Rust Installer
    when: cargo_exists is failed
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust

  - name: install rust/cargo
    when: cargo_exists is failed
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust
